version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rakesh
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: rakesh
    ports:
      - "5432:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_ui
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: todo_user
      PMA_PASSWORD: rakesh
    ports:
      - "5050:80"
    depends_on:
      - mysql
    networks:
      - todo-net

  app:
    image: todo-app:1.0
    container_name: todo_app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: rakesh
    ports:
      - "9090:8080"
    networks:
      - todo-net

volumes:
  mysql_data:

networks:
  todo-net:
    driver: bridge
